name: Deploy LiveKit Agent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Install LiveKit CLI
        run: |
          npm install -g @livekit/cli
          lk --version

      - name: Authenticate with LiveKit Cloud
        run: |
          lk cloud auth --api-key ${{ secrets.LIVEKIT_API_KEY }} --api-secret ${{ secrets.LIVEKIT_API_SECRET }}

      - name: Deploy Agent
        run: |
          lk agent deploy
        
